.releaserc.js

fix: deploy packages on rubygems

---

.rubocop.yml
agent_ruby.gemspec

fix: ci deploy agent_ruby

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/schema/schema_collection_decorator_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/decorators/collection_decorator.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/decorators/schema/schema_collection_decorator.rb
packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/collection_spec.rb

allow countable method for schema

feat: add schema decorator support

---

packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/related/list_related.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/show.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/store.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/update.rb
packages/forest_admin_agent/lib/forest_admin_agent/serializer/forest_serializer.rb
packages/forest_admin_agent/lib/forest_admin_agent/serializer/forest_serializer_override.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/store_spec.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/active_record_serializer.rb

feat(serializer): serialize hash instead of an active record object

---

.rubocop.yml
packages/forest_admin_agent/lib/forest_admin_agent/http/Exceptions/conflict_error.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/Exceptions/forbidden_error.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/Exceptions/http_exception.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/Exceptions/require_approval.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/Exceptions/unprocessable_error.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/action/action.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/permissions.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/smart_action_checker.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/condition_tree_parser.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
packages/forest_admin_agent/spec/forest_admin_agent_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/action/action_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/charts/charts_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/services/smart_action_checker_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/condition_tree_parser_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/query_string_parser_spec.rb
packages/forest_admin_datasource_active_record/spec/forest_admin_datasource_active_record_spec.rb
packages/forest_admin_datasource_customizer/spec/forest_admin_datasource_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/utils/hash_helper.rb
packages/forest_admin_datasource_toolkit/spec/forest_admin_datasource_toolkit_spec.rb
packages/forest_admin_rails/lib/forest_admin_rails/engine.rb

feat(action): add permission on action routes

---

.rubocop.yml
packages/forest_admin_agent/spec/lib/forest_admin_agent/builder/agent_factory_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/charts/charts_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/associate_related_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/count_related_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/dissociate_related_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/list_related_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/update_related_spec.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/datasource_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_datasource_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/datasource_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/publication/publication_datasource_decorator_spec.rb

feat: add publication decorator support

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/datasource_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_collection/rename_collection_datasource_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_collection/rename_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/datasource_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/rename_collection/rename_collection_datasource_decorator_spec.rb
packages/forest_admin_datasource_customizer/spec/shared/column_schema_factory.rb
packages/forest_admin_datasource_customizer/spec/shared/factory.rb
packages/forest_admin_datasource_customizer/spec/spec_helper.rb

feat: add rename collection decorator support

---

.rubocop.yml
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/create_relations/create_relations_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/update_relations/update_relations_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/write_datasource_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/write_replace/write_customization_context.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/write_replace/write_replace_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/create_relations/collection_mixed_relations_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/create_relations/collection_multiple_many_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/create_relations/collection_multiple_one_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/create_relations/collection_single_many_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/create_relations/collection_single_one_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/update_relations/collection_many_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/update_relations/collection_one_to_one_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/write_replace/collection_basics_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/write_replace/collection_relation_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/write_replace/collection_simple_creation_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/write/write_replace/collection_simple_update_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/field_validator.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/record_validator.rb
packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/validations/record_validator_spec.rb

feat:  add write decorator support

---

.rubocop.yml
packages/forest_admin_datasource_active_record/Gemfile
packages/forest_admin_datasource_customizer/forest_admin_datasource_customizer.gemspec
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/binary/binary_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/binary/binary_helper.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/binary/binary_collection_decorator_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/operators.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/decorators/collection_decorator.rb
packages/forest_admin_rails/lib/forest_admin_rails/engine.rb

feat: add binary decorator support

---

packages/forest_admin_agent/lib/forest_admin_agent/builder/agent_factory.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/permissions.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb
packages/forest_admin_rails/app/controllers/forest_admin_rails/forest_controller.rb
packages/forest_admin_rails/config/initializers/forest_admin_error_subscriber.rb
packages/forest_admin_rails/config/routes.rb
packages/forest_admin_rails/lib/forest_admin_rails/engine.rb

feat: add logs in dev mode

---

packages/forest_admin_agent/lib/forest_admin_agent/auth/oidc_client_manager.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/forest_admin_api_requester.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/ip_whitelist.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/services/ip_whitelist_spec.rb

chore: ipwhitelist now uses ForestAdminApiRequester

---

.rubocop.yml
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/plugins/add_external_relation.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/plugins/import_field.rb

feat(plugin): add new import field plugin

---

.rubocop.yml
packages/forest_admin_agent/Gemfile
packages/forest_admin_agent/lib/forest_admin_agent/http/router.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/action/actions.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/action/action_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/action/actions_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
packages/forest_admin_datasource_active_record/Gemfile
packages/forest_admin_datasource_customizer/Gemfile
packages/forest_admin_rails/Gemfile

fix: gemspecs load packages from rubygems

---

packages/forest_admin_agent/lib/forest_admin_agent/builder/agent_factory.rb
packages/forest_admin_agent/lib/forest_admin_agent/http/router.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/security/scope_invalidation.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/security/scope_invalidation_spec.rb

feat: add scope invalidation endpoint

---

packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/active_record_serializer.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/computed/utils/computed_field.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/computed/utils/flattener.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/computed/utils/flattener_spec.rb

fix(computed): allow to use computed decorator with nested relations

---

.rubocop.yml
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/datasource.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb

fix(introspection): ignore models that do not have primary key 

---

packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/relation.rb
packages/forest_admin_datasource_active_record/spec/dummy/app/models/category.rb
packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/parser/relation_spec.rb

fix(active_record): introspection should not crash on an unconventional relation

---

packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/forest_value_converter.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/form_layout_element.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/action/base_action_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_field_factory.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_layout_element.rb
packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/components/actions/action_field_factory_spec.rb

feat(form): add HtmlBlock layout element

---

packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_layout_element.rb

fix(form): remove type attribute from schema layout element

---

packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/related/dissociate_related.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/dissociate_related_spec.rb

fix(permissions): properly check permissions when dissociating or deleting related resources

---

packages/forest_admin_agent/lib/forest_admin_agent/http/router.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/capabilities/collections.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/frontend_filterable.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_field.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/capabilities/collections_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/charts/charts_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/list_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/list_related_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/query_string_parser_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/frontend_filterable_spec.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_field_spec.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/relation/relation_collection_decorator.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/condition_tree_factory.rb
packages/forest_admin_rails/app/controllers/forest_admin_rails/forest_controller.rb

feat(capabilities): add new collections route

---

packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/capabilities/collections_spec.rb
packages/forest_admin_datasource_customizer/spec/shared/caller.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/caller.rb
packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/components/contracts/collection_contract_spec.rb
packages/forest_admin_datasource_toolkit/spec/shared/caller.rb

feat: add request ip to user context

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator_spec.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/many_to_many_schema.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/many_to_one_schema.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/one_to_many_schema.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/one_to_one_schema.rb
packages/forest_admin_datasource_toolkit/sig/forest_admin_datasource_toolkit/schema/relations/many_relation_schema.rbs
packages/forest_admin_datasource_toolkit/sig/forest_admin_datasource_toolkit/schema/relations/many_to_many_schema.rbs
packages/forest_admin_datasource_toolkit/sig/forest_admin_datasource_toolkit/schema/relations/single_relation_schema.rbs

fix(rename decorator): properly map relation when renaming pk field 

---

.github/workflows/build.yml
.releaserc.js
.rubocop.yml
packages/forest_admin_test_toolkit/.gitignore
packages/forest_admin_test_toolkit/Gemfile
packages/forest_admin_test_toolkit/LICENSE
packages/forest_admin_test_toolkit/Rakefile
packages/forest_admin_test_toolkit/bin/console
packages/forest_admin_test_toolkit/bin/setup
packages/forest_admin_test_toolkit/forest_admin_test_toolkit.gemspec
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit.rb
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit/factory/caller.rb
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit/factory/collection.rb
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit/factory/column.rb
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit/factory/datasource.rb
packages/forest_admin_test_toolkit/lib/forest_admin_test_toolkit/version.rb

feat: add package to provide test tools 

---

packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_collection.rb
packages/forest_admin_agent/spec/shared/factory.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/segment/segment_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/datasource_customizer_spec.rb
packages/forest_admin_datasource_customizer/spec/shared/factory.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/collection_spec.rb
packages/forest_admin_datasource_toolkit/spec/shared/factory.rb

fix(collection): add missing function enable_search and add_segments

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator_spec.rb

fix(search): collection is not always searchable

---

packages/forest_admin_datasource_active_record/Gemfile
packages/forest_admin_datasource_active_record/Gemfile-test
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/column.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb
packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/parser/column_spec.rb
packages/forest_admin_datasource_active_record/spec/spec_helper.rb

fix(active_record): return default string type and add log when field type is unknown

---

.github/workflows/build.yml
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator_spec.rb

fix(polymorphic): prevent update path when not rename polymorphic relation field

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/result_builder.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/action/action_collection_decorator_spec.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/action/result_builder_spec.rb

fix: display custom success/error messages for actions

---

packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb

fix: allow replace_search to accept a block

---

packages/forest_admin_agent/lib/forest_admin_agent/routes/charts/charts.rb
packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/charts/charts_spec.rb

fix(charts): properly format week of year

---

.codeclimate.yml

chore(codeclimate): remove rubocop from codeclimate

---

.rubocop.yml
Gemfile
packages/forest_admin_agent/lib/forest_admin_agent/routes/charts/charts.rb
packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/native_query.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/ip_whitelist.rb
packages/forest_admin_agent/lib/forest_admin_agent/services/permissions.rb
packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action_field_widget.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/relation.rb
packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query_aggregate.rb
packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/utils/query_aggregate_spec.rb
packages/forest_admin_datasource_active_record/spec/spec_helper.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/relation/relation_collection_decorator.rb
packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
packages/forest_admin_datasource_mongoid/lib/forest_admin_datasource_mongoid/utils/add_null_values.rb
packages/forest_admin_datasource_mongoid/lib/forest_admin_datasource_mongoid/utils/helpers.rb
packages/forest_admin_datasource_mongoid/lib/forest_admin_datasource_mongoid/utils/pipeline/lookup_generator.rb
packages/forest_admin_datasource_mongoid/lib/forest_admin_datasource_mongoid/utils/pipeline/reparent_generator.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/aggregation.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/nodes/condition_tree.rb
packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/sort.rb

fix: reorder filter and grouping operations in QueryAggregate

---

packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/column.rb
packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20251002103347_add_timestamptz_field_to_users.rb
packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/parser/column_spec.rb

feat(active-record): support timestamptz column type
