ForestAdmin/agent-ruby

- .rubocop.yml
- packages/forest_admin_agent/forest_admin_agent.gemspec
- packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec
- packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec
- packages/forest_admin_rails/forest_admin_rails.gemspec
> fix: ci remove rubygems_mfa_required

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb
- packages/forest_admin_agent/lib/forest_admin_agent/utils/id.rb
- packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/list_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/id_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/query_string_parser_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/context/agent_customization_context.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/context/collection_customization_context.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/context/relaxed_wrappers/relaxed_collection.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/context/relaxed_wrappers/relaxed_data_source.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/schema/schema_collection_decorator.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/schema/schema_collection_decorator_spec.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
- packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/collection_spec.rb
> feat(decorator): add search support

- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/validation/validation_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/validation/validation_collection_decorator_spec.rb
> feat: add validation support

- .rubocop.yml
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/sort/sort_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/relation/relation_collection_decorator_spec.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/sort/sort_collection_decorator_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/page.rb
> feat: add sort decorator support

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/count.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/count_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/store_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/update_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/aggregation.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/decorators/collection_decorator.rb
> feat: add rename field decorator support

- packages/forest_admin_agent/spec/shared/factory.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/segment/segment_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/collection_customizer_spec.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/segment/segment_collection_decorator_spec.rb
- packages/forest_admin_datasource_customizer/spec/shared/factory.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
- packages/forest_admin_datasource_toolkit/spec/shared/factory.rb
> feat: add segment decorator support

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/query_string_parser_spec.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
> feat: support multi field sorting from frontend

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/frontend_validation_utils.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/frontend_validation_utils_spec.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/context/relaxed_wrappers/relaxed_collection_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/decorators/collection_decorator.rb
- packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/decorators/collection_decorator_spec.rb
> feat: add native driver support

- packages/forest_admin_agent/lib/forest_admin_agent/serializer/forest_serializer_override.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/datasource.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/datasource_customizer.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/datasource_customizer_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb
> feat: expose plugin to datasource-customizer

- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/operators_equivalence/operators_equivalence_collection_decorator.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb
> fix: search behaviour 

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/computed/utils/flattener.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/utils/collection.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/field_validator.rb
- packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/validations/field_validator_spec.rb
> fix: decorators and toolkit for work with polymorphic relations

- packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/action_collection_decorator.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/form_layout_element.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/action/base_action_spec.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_field_factory.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_layout_element.rb
> feat(action_form): add row layout customization

- packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/action/base_action_spec.rb
> feat(action_form): add description and submit button customization

- packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_action_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/form_layout_element.rb
> feat(form): add support of static form with layout elements

- packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb
- packages/forest_admin_agent/lib/forest_admin_agent/utils/context_variables.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/capabilities/collections_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/context_variables_injector_spec.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/context_variables_spec.rb
> fix: ensure correct values are returned for user tags in context variables

- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/builder/agent_factory.rb
- packages/forest_admin_agent/lib/forest_admin_agent/services/smart_action_checker.rb
- packages/forest_admin_datasource_active_record/Gemfile
- packages/forest_admin_datasource_active_record/Gemfile-test
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/aggregation.rb
> fix(permission): get approval conditions by role id 

- packages/forest_admin_agent/lib/forest_admin_agent/routes/charts/charts.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/charts/charts_spec.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query_aggregate.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/lazy_join/lazy_join_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/lazy_join/lazy_join_collection_decorator_spec.rb
> feat: add lazy join decorator to improve performance

- packages/forest_admin_agent/lib/forest_admin_agent/utils/caller_parser.rb
- packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb
- packages/forest_admin_datasource_customizer/spec/shared/caller.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/caller.rb
- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/aggregation.rb
- packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/components/contracts/collection_contract_spec.rb
- packages/forest_admin_datasource_toolkit/spec/shared/caller.rb
> feat(caller): add project and environment

- .github/workflows/build.yml
- .rubocop.yml
- packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb
- packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/schema_emitter_spec.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb
- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/datasource.rb
- packages/forest_admin_datasource_active_record/spec/dummy/app/models/company.rb
- packages/forest_admin_datasource_active_record/spec/dummy/app/models/user.rb
- packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20230810095726_create_companies.rb
- packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20230810095727_create_companies_users.rb
- packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/collection_spec.rb
- packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/datasource_spec.rb
> fix(relation): add support of has_and_belongs_to_many relations

- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator.rb
- packages/forest_admin_datasource_customizer/spec/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator_spec.rb
> fix(publication): log warning when relation field is unknown and return false

- packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb
- packages/forest_admin_datasource_active_record/spec/dummy/app/models/account.rb
- packages/forest_admin_datasource_active_record/spec/dummy/app/models/account_history.rb
- packages/forest_admin_datasource_active_record/spec/dummy/app/models/supplier.rb
- packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20250121150630_create_suppliers.rb
- packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20250121150710_create_account_histories.rb
- packages/forest_admin_datasource_active_record/spec/dummy/db/migrate/20250121150713_create_accounts.rb
- packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/collection_spec.rb
- packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/datasource_spec.rb
- packages/forest_admin_datasource_active_record/spec/lib/forest_admin_datasource_active_record/utils/query_spec.rb
- packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb
> fix(relation): support has_one through when through collection has 2 belongs_to

- .github/workflows/notify-ci-failure.yml
- .github/workflows/vulnerability-scan.yml
> ci(security / build): send slack message for security report and build failure

- packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/caller.rb
- packages/forest_admin_datasource_toolkit/spec/lib/forest_admin_datasource_toolkit/components/caller_spec.rb
> feat(caller): allow extra arguments
